version: '3.8'

services:
  app:
    image: dockdesper/my-node-app:latest
    ports:
      - "3005:3000"
    depends_on:
      - mysql
    env_file:
      - .env
  
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Utilise la variable d'environnement pour le mot de passe root
      MYSQL_DATABASE: ${DB_NAME}  # Utilise la variable d'environnement pour le nom de la base de données
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
