version: '3.8'

services:
  app:
    image: dockdesper/my-node-app:latest
    ports:
      - "3005:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=192.168.0.107
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=test_db
  
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
